# Wed Oct 25 16:19:35 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Wed Oct 25 16:19:35 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {alterId: 0, cipher: none, network: ws, port: 2082, server: 206.168.190.219, skip-cert-verify: false, tls: false, type: vmess, uuid: e31ca750-71f7-11ee-b920-1239d0255272, ws-opts: {path: /vmws},"name":"US_206.168.190.219_10252023be97-365vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 65500, server: 138.68.136.50, skip-cert-verify: false, tls: false, type: vmess, uuid: 6b2e381c-8214-47c7-aa73-54c803ef1d22, ws-opts: {path: /},"name":"GB_138.68.136.50_10252023be97-370vmess"}
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 54.151.244.95, type: ss,"name":"SG_54.151.244.95_10252023be97-373ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.24, type: ss,"name":"GB_198.244.231.24_10252023be97-374ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.204.80, type: ss,"name":"FR_162.19.204.80_10252023be97-388ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 57.128.32.84, type: ss,"name":"FR_57.128.32.84_10252023be97-395ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 46.183.184.64, type: ss,"name":"HR_46.183.184.64_10252023be97-400ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.27, type: ss,"name":"GB_198.244.231.27_10252023be97-406ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.74, type: ss,"name":"GB_198.244.231.74_10252023be97-413ss"}
  - {cipher: chacha20-ietf-poly1305, password: NeVavl43FD6DgFoim7S6HGks, port: 51348, server: uk-c2261789.nip.io, type: ss,"name":"UA_194.38.23.137_10252023be97-431ss"}
  - {cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, port: 810, server: 51.178.87.37, type: ss,"name":"FR_51.178.87.37_10252023be97-460ss"}
  - {cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, port: 810, server: 185.172.113.182, type: ss,"name":"JP_185.172.113.182_10252023be97-465ss"}
  - {password: telegram-id-directvpn, port: 22222, server: 13.43.69.5, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"GB_13.43.69.5_10252023be97-468trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: ophelia.mom, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: ophelia.mom}},"name":"CLOUDFLARE_172.67.207.114_10252023be97-471vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 45.155.249.151, servername: tms.dingtalk.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 9d5e69d2-46cf-4865-95fe-a2ee8c52a013, ws-opts: {path: /},"name":"NL_45.155.249.151_10252023be97-487vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.221.224, type: ss,"name":"FR_51.159.221.224_10252023be97-488ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: cloudflare.binghe.design, skip-cert-verify: false, tls: true, type: vmess, uuid: 4548b8de-c6f5-41f2-8cb6-723c8db8ed03, ws-opts: {path: /, headers: {Host: us.binghe.design}},"name":"CLOUDFLARE_104.16.68.38_10252023be97-467vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: cc2.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {Host: cc2.shabijichang.com}},"name":"CLOUDFLARE_104.21.75.246_10252023be97-511vmess"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 103.75.118.27, type: ss,"name":"JP_103.75.118.27_10252023be97-521ss"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: odelia.autos, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: odelia.autos}},"name":"CLOUDFLARE_104.21.21.88_10252023be97-504vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.202.175, type: ss,"name":"NL_51.158.202.175_10252023be97-529ss"}
  - {alterId: 64, cipher: auto, network: ws, port: 30000, server: 45.199.138.186, skip-cert-verify: true, tls: true, type: vmess, uuid: 4ec0ae62-de09-4029-904a-0313d4628ecf, ws-opts: {path: /path/1697376782879, headers: {host: www.19229362.xyz}},"name":"NL_45.199.138.186_10252023be97-533vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.210.173, type: ss,"name":"FR_51.159.210.173_10252023be97-535ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 146.59.110.167, type: ss,"name":"FR_146.59.110.167_10252023be97-542ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 20036, server: 222.187.238.9, skip-cert-verify: false, tls: false, type: vmess, uuid: ee0a4b54-be8d-4f56-be4d-521bd1ae443d, ws-opts: {path: /},"name":"CN_222.187.238.9_10252023be97-547vmess"}
