# Fri Nov  3 08:15:48 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Fri Nov  3 08:15:48 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-gcm, password: faBAoD54k87UJG7, port: 2376, server: ak1633.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"PL_51.77.53.200_11032023509c-382ss"}
  - {cipher: aes-256-gcm, password: pKEW8JPByTVTLtM, port: 4444, server: ak1720.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"FR_145.239.6.202_11032023509c-384ss"}
  - {cipher: aes-256-gcm, password: KixLvKzwjekG00rm, port: 8080, server: ak1810.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"DE_145.239.1.100_11032023509c-385ss"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: oliv.beauty, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: oliv.beauty}},"name":"CLOUDFLARE_104.21.4.29_11032023509c-397vmess"}
  - {cipher: aes-256-gcm, password: FoOiGlkAA9yPEGP, port: 7306, server: 38.143.66.55, type: ss,"name":"US_38.143.66.55_110220234b2e-452ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 89.187.179.192, type: ss,"name":"US_89.187.179.192_110220234b2e-456ss"}
  - {cipher: chacha20-ietf-poly1305, password: g13S7doXar0A, port: 443, server: 205.134.180.137, type: ss,"name":"US_205.134.180.137_110220234b2e-464ss"}
