# Sun Sep 24 11:45:34 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Sun Sep 24 11:45:34 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: vps.pangchun.top, skip-cert-verify: false, tls: true, type: vmess, uuid: 5d888c70-ce7a-4ade-f4f6-1d747f8e9328, ws-opts: {path: /cfvmess, headers: {Host: vps.pangchun.top}},"name":"CLOUDFLARE_172.67.146.246_0924202365d3-274vmess"}
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 43.202.67.172, type: ss,"name":"KR_43.202.67.172_0924202365d3-295ss"}
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 43.207.233.98, type: ss,"name":"JP_43.207.233.98_0924202365d3-300ss"}
  - {cipher: aes-256-gcm, password: g5MeD6Ft3CWlJId, port: 5004, server: ak1650.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"FR_149.202.82.172_0924202365d3-315ss"}
  - {cipher: chacha20-ietf-poly1305, password: ezesBXesf3RKBCp1vqKuIx, port: 8080, server: 143.42.54.107, type: ss,"name":"DE_143.42.54.107_0924202365d3-321ss"}
  - {cipher: aes-256-cfb, obfs: tls1.2_ticket_auth, obfs-param: "", password: 3g0dHlKME, port: 32001, protocol: origin, protocol-param: "", server: sg-am3.eqsunshine.com, type: ssr,"name":"SG_54.169.51.15_0924202365d3-331ssr"}
  - {cipher: chacha20-ietf-poly1305, password: XvK0ltH67Xhv9ht9RhYsFy, port: 8080, server: 139.162.163.64, type: ss,"name":"DE_139.162.163.64_0924202365d3-342ss"}
  - {password: LYaOvuNXdQGTZNonhlRUKqOJcKVihzKY, port: 889, server: 65.75.220.76, skip-cert-verify: false, sni: s3.cjhh.beauty, type: trojan,"name":"US_65.75.220.76_0924202365d3-359trojan"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 137.175.23.177, skip-cert-verify: false, tls: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /path/1694516064215, headers: {Host: www.22866947.xyz}},"name":"US_137.175.23.177_0924202365d3-361vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: f.6446xtsy.buzz, skip-cert-verify: false, tls: true, type: vmess, uuid: f7aea457-b58a-4e2c-aba0-20019dd89fff, ws-opts: {path: /ask6446888, headers: {Host: f.6446xtsy.buzz}},"name":"CLOUDFLARE_104.21.34.126_0924202365d3-348vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.24.183.89, tls: true, type: vmess, uuid: 55da74e0-fc9e-4704-9c70-eba94297e1ab, ws-opts: {path: /pNV7izRFLO8rGCkIH66kMFPa, headers: {host: auto.karop.homes}},"name":"CLOUDFLARE_104.24.183.89_0924202365d3-411vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 31.172.67.43, type: ss,"name":"RU_31.172.67.43_0924202365d3-416ss"}
