# Mon Oct 16 08:19:35 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Mon Oct 16 08:19:35 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 172.64.152.228, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: '/odelia.autos:443/linkvws', headers: {Host: sub.yifenjichang.top}},"name":"CLOUDFLARE_172.64.152.228_101620230d46-333vmess"}
  - {cipher: chacha20-ietf-poly1305, password: tvX1v#NSFP_LG_bJ, port: 801, server: ak1837.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"US_169.197.141.186_101620230d46-340ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: wnd2.shabijichang.com, skip-cert-verify: true, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {host: wnd2.shabijichang.com}},"name":"CLOUDFLARE_172.64.80.1_101620230d46-338vmess"}
  - {network: tcp, password: ee5d4ca4-cb15-4201-ba4f-4709b5a833d4, port: 443, server: v234.jsvpn.xyz, skip-cert-verify: true, type: trojan,"name":"RU_46.17.45.159_101620230d46-345trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: waynn.makeup, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: waynn.makeup}},"name":"CLOUDFLARE_172.67.183.110_101620230d46-356vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 110, server: 143.244.43.216, type: ss,"name":"CA_143.244.43.216_101620230d46-369ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.18.35.28, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: '/odelia.autos:443/linkvws', headers: {Host: sub.yifenjichang.top}},"name":"CLOUDFLARE_104.18.35.28_101620230d46-371vmess"}
  - {network: tcp, password: telegram-id-privatevpns, port: 22222, server: 15.188.43.83, skip-cert-verify: true, sni: trj.rollingnext.co.uk, type: trojan,"name":"FR_15.188.43.83_101620230d46-375trojan"}
  - {cipher: aes-256-gcm, password: KixLvKzwjekG00rm, port: 8080, server: ak1661.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"GB_51.68.206.229_101620230d46-378ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 13337, server: 83.229.70.215, skip-cert-verify: true, tls: true, type: vmess, uuid: bdd22841-c4d2-4aa8-acf2-95aa9125f159, ws-opts: {path: /},"name":"IL_83.229.70.215_101620230d46-387vmess"}
  - {password: telegram-id-directvpn, port: 22222, server: 13.48.87.145, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"SE_13.48.87.145_101620230d46-388trojan"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 123.253.34.235, type: ss,"name":"MY_123.253.34.235_101620230d46-395ss"}
  - {alterId: 0, cipher: auto, network: tcp, port: 20492, server: 168.75.76.226, skip-cert-verify: true, tls: false, type: vmess, uuid: 259e1c70-fa0f-4759-b959-1e5630eac8de,"name":"BR_168.75.76.226_101620230d46-409vmess"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 185.47.255.219, type: ss,"name":"PR_185.47.255.219_101620230d46-412ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 217.163.76.220, skip-cert-verify: false, tls: false, type: vmess, uuid: 11111ad6-32cd-4bbb-9247-421878e0c7bd, ws-opts: {path: /cctv13.m3u8, headers: {Host: us05.cctvvip.tk}},"name":"GB_217.163.76.220_101620230537-421vmess"}
  - {cipher: chacha20-ietf-poly1305, password: R9Xc4dHXGv3c, port: 443, server: 205.134.180.143, type: ss,"name":"US_205.134.180.143_101620230537-433ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.20.9.79, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_104.20.9.79_101620230537-434vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 31235, server: kr-cdn-6273819.starnetcn.top, skip-cert-verify: false, tls: false, type: vmess, uuid: 8e73f50a-35cd-4235-9c18-a3e061e7bc9f, ws-opts: {path: /315d825893fc34aca0231ab967157986, headers: {Host: jxhoisldy718922.starnetcn.top}},"name":"JP_43.207.221.236_101620230d46-405vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.27.1.133, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_104.27.1.133_101620230537-441vmess"}
