# Thu Sep 28 16:15:51 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Thu Sep 28 16:15:51 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {alterId: 0, cipher: auto, client-fingerprint: chrome, network: ws, port: 443, server: api.jquery.com, skip-cert-verify: false, tfo: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: '/oliv.beauty:443/linkvws', headers: {Host: sub.yifenjichang.top}},"name":"CLOUDFLARE_104.18.213.12_092820231071-281vmess"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: alvvin.click, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {host: alvvin.click}},"name":"CLOUDFLARE_104.21.50.177_09282023c53e-287vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 194.62.42.77, skip-cert-verify: true, tls: false, type: vmess, uuid: 14665d49-17ee-4fd7-b1de-19d98e4b8e27, ws-opts: {path: /vmess},"name":"IL_194.62.42.77_09282023c53e-303vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 23.95.164.190, skip-cert-verify: false, tls: false, type: vmess, uuid: 2111eba4-fca4-406a-aa88-abb5131c7088, ws-opts: {path: /bb},"name":"US_23.95.164.190_09282023c53e-305vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: hcm02.4ghatde.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 7c810704-e3d7-4e14-92c1-a8e2f63dd52d, ws-opts: {path: /svip2.4ghatde.com, headers: {Host: hcm02.4ghatde.com}},"name":"VN_103.161.173.56_09282023c53e-306vmess"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: ophelia.mom, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: ophelia.mom}},"name":"CLOUDFLARE_104.21.53.12_09282023c53e-301vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 64.32.24.222, skip-cert-verify: true, tls: true, type: vmess, uuid: cff9d860-7330-4ee1-b072-7142ddf1571d, ws-opts: {path: /path/080822272914, headers: {host: www.82615355.xyz}},"name":"US_64.32.24.222_09282023c53e-324vmess"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 195.154.169.198, type: ss,"name":"FR_195.154.169.198_09282023c53e-337ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: sg2.wyhkaa0.cf, skip-cert-verify: false, tls: false, type: vmess, uuid: fc426675-5daa-46c0-d998-61f9f5323e3f, ws-opts: {path: '/TG:@hkaa0', headers: {Host: sg2.wyhkaa0.cf}},"name":"CLOUDFLARE_172.67.190.69_09282023c53e-320vmess"}
  - {cipher: chacha20-ietf-poly1305, password: XlUFgoOqDlVqlZFD3Js0YA, port: 8080, server: masting.xyz, type: ss,"name":"DE_139.162.143.111_09282023c53e-346ss"}
  - {password: ee4657c907, port: 443, server: uk1.connecton.surf, skip-cert-verify: false, type: trojan,"name":"GB_198.244.252.93_09282023c53e-318trojan"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 137.175.23.177, tls: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /path/1694516064215, headers: {host: www.22866947.xyz}},"name":"US_137.175.23.177_09282023c53e-364vmess"}
