# Wed Oct 11 16:16:18 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Wed Oct 11 16:16:18 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: chacha20-ietf-poly1305, password: 5cp9Z3iWnJZ2, port: 443, server: www.outline.network.ak1889.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"US_205.134.180.151_101120237946-193ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 5.188.108.10, type: ss,"name":"PL_5.188.108.10_101120237946-224ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 165.231.120.102, type: ss,"name":"NO_165.231.120.102_101120237946-229ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 141.95.64.70, type: ss,"name":"FR_141.95.64.70_101120237946-244ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.14.40, type: ss,"name":"FR_51.159.14.40_101120237946-248ss"}
  - {alterId: 0, cipher: auto, network: tcp, port: 22324, server: 198.57.27.212, type: vmess, uuid: 04621bae-ab36-11ec-b909-0242ac120002,"name":"CA_198.57.27.212_101120237946-252vmess"}
