# Fri Oct 20 16:15:44 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Fri Oct 20 16:15:44 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.59.168, type: ss,"name":"FR_162.19.59.168_10202023b220-297ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.195.96, type: ss,"name":"FR_51.158.195.96_10202023b220-302ss"}
  - {cipher: aes-256-gcm, password: PCnnH6SQSnfoS27, port: 8091, server: 167.88.63.44, type: ss,"name":"US_167.88.63.44_10202023b220-309ss"}
  - {cipher: aes-128-gcm, password: shadowsocks, port: 443, server: 212.102.53.195, type: ss,"name":"GB_212.102.53.195_10202023b220-321ss"}
  - {cipher: chacha20-ietf-poly1305, password: Wc9mwaXoVeyznoAXxvaxok, port: 33108, server: 3.71.92.131, type: ss,"name":"DE_3.71.92.131_10202023b220-327ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.222.29, type: ss,"name":"FR_51.159.222.29_10202023b220-332ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: mm3.shabijichang.com, skip-cert-verify: true, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {host: mm3.shabijichang.com}},"name":"CLOUDFLARE_172.64.80.1_10202023b220-305vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: asb2.shabijichang.com, skip-cert-verify: true, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {host: asb2.shabijichang.com}},"name":"CLOUDFLARE_172.67.184.13_10202023b220-322vmess"}
  - {password: telegram-id-directvpn, port: 22222, server: 3.79.77.105, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"DE_3.79.77.105_10202023b220-347trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: de1-vmess.greenssh.xyz, skip-cert-verify: true, tls: false, type: vmess, uuid: 12612b4e-e426-4b7c-84bd-4a02850abb1e, ws-opts: {path: /vmess, headers: {host: de1-vmess.greenssh.xyz}},"name":"FR_135.125.190.73_10202023b220-349vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2052, server: dx1.992688.xyz, skip-cert-verify: false, tls: false, type: vmess, uuid: b63efdd5-bdb8-4eb4-f918-9846cd7321e6, ws-opts: {path: /, headers: {Host: vcus1.vpn66.eu.org}},"name":"CLOUDFLARE_172.67.39.17_10202023b220-360vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 57.129.1.19, type: ss,"name":"DE_57.129.1.19_10202023b220-364ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 57.128.32.76, type: ss,"name":"FR_57.128.32.76_10202023b220-371ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.34, type: ss,"name":"GB_198.244.231.34_10202023b220-381ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 192.71.249.78, type: ss,"name":"BE_192.71.249.78_10202023b220-395ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 192.71.211.161, type: ss,"name":"IM_192.71.211.161_10202023b220-401ss"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 3389, server: 38.143.66.87, type: ss,"name":"US_38.143.66.87_10202023b220-406ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 213.169.137.221, type: ss,"name":"CY_213.169.137.221_10202023b220-411ss"}
  - {cipher: aes-256-cfb, password: eIW0Dnk69454e6nSwuspv9DmS201tQ0D, port: 8099, server: 139.162.236.79, type: ss,"name":"GB_139.162.236.79_10202023b220-414ss"}
