# Wed Oct 18 08:16:56 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Wed Oct 18 08:16:56 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-cfb, obfs: tls1.2_ticket_auth, obfs-param: cloudfront.net, password: iFqnzSscN, port: 8083, protocol: origin, protocol-param: "", server: 150.107.46.21, type: ssr,"name":"HK_150.107.46.21_10182023dc95-259ssr"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 137.175.23.177, tls: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /path/1694516064215, headers: {host: www.22866947.xyz}},"name":"US_137.175.23.177_10182023dc95-261vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 8443, server: 104.21.36.26, skip-cert-verify: false, tls: true, type: vmess, uuid: 1cec1ebc-b489-4769-f2d9-e079b5832a60, ws-opts: {path: /cloudconeaaa, headers: {Host: cloudconeaaa.gorgorchicken.one}},"name":"CLOUDFLARE_104.21.36.26_10182023dc95-263vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: cc3.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {Host: cc3.shabijichang.com}},"name":"CLOUDFLARE_104.21.75.246_10182023dc95-257vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: wnd2.shabijichang.com, skip-cert-verify: true, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {host: wnd2.shabijichang.com}},"name":"CLOUDFLARE_172.67.184.13_10182023dc95-258vmess"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: ophelia.mom, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {host: ophelia.mom}},"name":"CLOUDFLARE_104.21.53.12_10182023dc95-277vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 3389, server: 142.202.48.7, type: ss,"name":"US_142.202.48.7_10182023dc95-284ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.19.240.189, tls: true, type: vmess, uuid: 55da74e0-fc9e-4704-9c70-eba94297e1ab, ws-opts: {path: /pNV7izRFLO8rGCkIH66kMFPa, headers: {host: auto.karop.homes}},"name":"CLOUDFLARE_104.19.240.189_10182023dc95-292vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2052, server: 172.67.192.114, skip-cert-verify: true, tls: false, type: vmess, uuid: c94dabd2-f8e8-4021-fd57-402239ed650a, ws-opts: {path: '/TG:@dns68', headers: {host: uk.putata.tk}},"name":"CLOUDFLARE_172.67.192.114_10182023dc95-296vmess"}
  - {network: tcp, password: telegram-id-privatevpns, port: 22222, server: 35.181.192.228, skip-cert-verify: true, sni: trj.rollingnext.co.uk, type: trojan,"name":"FR_35.181.192.228_10182023dc95-320trojan"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 185.180.12.81, type: ss,"name":"AT_185.180.12.81_10182023dc95-323ss"}
  - {network: tcp, password: 44c5578a7c, port: 443, server: 37.143.129.56, skip-cert-verify: true, sni: fi1.connecton.surf, type: trojan,"name":"FI_37.143.129.56_10182023dc95-338trojan"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.19.210, type: ss,"name":"FR_162.19.19.210_10182023dc95-342ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.104.104, type: ss,"name":"FR_51.159.104.104_10182023dc95-372ss"}
  - {password: telegram-id-directvpn, port: 22222, server: 35.158.187.4, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"DE_35.158.187.4_10182023dc95-379trojan"}
  - {cipher: chacha20-ietf-poly1305, password: XlUFgoOqDlVqlZFD3Js0YA, port: 8080, server: 194.195.254.63, type: ss,"name":"AU_194.195.254.63_10182023dc95-392ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 5.188.6.8, type: ss,"name":"UA_5.188.6.8_10182023dc95-398ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 2052, server: lt1.992688.xyz, skip-cert-verify: true, tls: false, type: vmess, uuid: fa5fc74f-0f0b-4221-82ba-dc7cd24e24e5, ws-opts: {path: /, headers: {host: vcus2.vpn66.eu.org}},"name":"CLOUDFLARE_162.159.242.217_10182023dc95-396vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2052, server: 162.159.137.86, skip-cert-verify: true, tls: false, type: vmess, uuid: fe5edf04-c2af-4ac5-84ee-16d43024decb, ws-opts: {path: /, headers: {host: us.wx.alue.link}},"name":"CLOUDFLARE_162.159.137.86_10182023dc95-405vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2052, server: cf.yx.alue.link, skip-cert-verify: true, tls: false, type: vmess, uuid: fe5edf04-c2af-4ac5-84ee-16d43024decb, ws-opts: {path: /, headers: {host: us.wx.alue.link}},"name":"CLOUDFLARE_104.26.4.42_10182023dc95-410vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 2096, server: 104.25.254.162, skip-cert-verify: true, tls: true, type: vmess, uuid: 12009e57-6fd8-46d6-94af-539514a7e7c7, ws-opts: {path: /, headers: {host: s1.shargh.shop}},"name":"CLOUDFLARE_104.25.254.162_10182023dc95-411vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 62.210.88.167, type: ss,"name":"FR_62.210.88.167_10182023dc95-414ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.221.227, type: ss,"name":"FR_51.159.221.227_10182023dc95-421ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 8080, server: dongtaiwang3.com, skip-cert-verify: true, tls: false, type: vmess, uuid: 969f1909-c0d3-4c30-813d-3aec5c838b7d, ws-opts: {path: /1IKYjV0r/, headers: {host: dongtaiwang8.dtku47.xyz}},"name":"CLOUDFLARE_23.227.38.86_10182023dc95-418vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 5000, server: 38.143.66.87, type: ss,"name":"US_38.143.66.87_101820238405-425ss"}
  - {cipher: aes-256-cfb, password: S7KwUu7yBy58S3Ga, port: 9042, server: 45.89.52.66, type: ss,"name":"TR_45.89.52.66_101820238405-428ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 57.128.32.84, type: ss,"name":"FR_57.128.32.84_101820238405-432ss"}
  - {alterId: 64, cipher: auto, network: ws, port: 30000, server: 156.225.67.104, skip-cert-verify: true, tls: true, type: vmess, uuid: 29a5d48e-24f1-48fd-a5e1-9a46cb31032f, ws-opts: {path: /path/1696944806961, headers: {host: www.41758112.xyz}},"name":"NL_156.225.67.104_101820238405-438vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 124.220.57.75, skip-cert-verify: false, tls: false, type: vmess, uuid: 1b3dd95b-f6dc-4f20-97aa-3b365358419c, ws-opts: {path: /},"name":"CN_124.220.57.75_101820238405-482vmess"}
  - {cipher: aes-128-cfb, password: shadowsocks, port: 443, server: 184.170.241.194, type: ss,"name":"US_184.170.241.194_101820238405-487ss"}
  - {cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, port: 804, server: 185.172.113.182, type: ss,"name":"JP_185.172.113.182_101820238405-493ss"}
  - {cipher: aes-256-gcm, password: cdBIDV42DCwnfIN, port: 8118, server: 51.77.53.200, type: ss,"name":"PL_51.77.53.200_101820238405-495ss"}
