# Wed Nov  1 08:16:52 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Wed Nov  1 08:16:52 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 46.183.184.60, type: ss,"name":"HR_46.183.184.60_103120232390-230ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.26, type: ss,"name":"GB_198.244.231.26_103120232390-245ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: cf-lt.sharecentre.online, skip-cert-verify: true, tls: false, type: vmess, uuid: 3d761afc-6dfd-49d9-9d0f-b79341391f26, ws-opts: {path: /api/v3/download.getFile, headers: {host: ssrsub.v006.ssrsub.com}},"name":"CLOUDFLARE_198.41.223.61_103120232390-261vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 30000, server: 156.249.18.151, skip-cert-verify: true, tls: true, type: vmess, uuid: 84d1de11-ce12-4a15-8312-1338356d4ac4, ws-opts: {path: /path/1698671600986, headers: {host: www.57424349.xyz}},"name":"NL_156.249.18.151_103120232390-266vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: v118a.ai88888.top, skip-cert-verify: false, tls: false, type: vmess, uuid: c97cf46e-1554-36cb-8b36-c3556b883dc4, ws-opts: {path: /526-dekDP6Otf, headers: {Host: v118a.ai88888.top}},"name":"CLOUDFLARE_172.67.129.249_103120232390-251vmess"}
  - {network: tcp, password: zwbdPys6Va, port: 16128, server: 94.131.13.159, skip-cert-verify: true, sni: vpnallpha.online, type: trojan,"name":"LT_94.131.13.159_103120232390-274trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.16.119.47, tls: true, type: vmess, uuid: 55da74e0-fc9e-4704-9c70-eba94297e1ab, ws-opts: {path: /pNV7izRFLO8rGCkIH66kMFPa, headers: {host: auto.karop.homes}},"name":"CLOUDFLARE_104.16.119.47_103120232390-276vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: octavi.cfd, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: octavi.cfd}},"name":"CLOUDFLARE_172.67.179.37_103120232390-283vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.202.173, type: ss,"name":"NL_51.158.202.173_103120232390-291ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.200.65, type: ss,"name":"FR_51.158.200.65_110120236f39-307ss"}
  - {cipher: aes-256-cfb, password: 2170f8, port: 14293, server: 45.55.2.232, type: ss,"name":"US_45.55.2.232_110120236f39-314ss"}
  - {cipher: chacha20-ietf-poly1305, password: XlUFgoOqDlVqlZFD3Js0YA, port: 8080, server: masting.xyz, type: ss,"name":"AU_172.105.175.239_110120236f39-325ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.21.4.29, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: oliv.beauty}},"name":"CLOUDFLARE_104.21.4.29_110120236f39-346vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 3306, server: 38.121.43.71, type: ss,"name":"US_38.121.43.71_110120236f39-353ss"}
  - {cipher: chacha20-ietf-poly1305, password: T1pb7XxxrolvPSb0u2xSOA, port: 8080, server: beacomf.xyz, type: ss,"name":"DE_172.104.243.93_110120236f39-356ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 62.210.88.139, type: ss,"name":"FR_62.210.88.139_110120236f39-359ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.159.221.223, type: ss,"name":"FR_51.159.221.223_110120236f39-365ss"}
  - {password: 7e23957d-535a-4dc6-9482-e6f44518da87, port: 443, server: sg1-reality.fp3kemyh-cm4s-2hak-2gb9-w3534umy2sq5.9d8f269f96b25232-759cbb36d6548597.kaufen, skip-cert-verify: false, sni: 13-231-155-134.nhost.00cdn.com, type: trojan,"name":"SG_139.162.53.28_110120236f39-339trojan"}
