# Thu Oct 26 08:16:18 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Thu Oct 26 08:16:18 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: br.gy.youxuan-1.66688888.xyz, skip-cert-verify: true, tls: false, type: vmess, uuid: efcb7d7c-c582-46f5-eeff-0e553342528d, ws-opts: {path: /tg@hkaa0, headers: {host: br.gy.youxuan-1.66688888.xyz}},"name":"CLOUDFLARE_104.21.12.86_1026202301d8-339vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.24, type: ss,"name":"GB_198.244.231.24_1026202301d8-341ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 57.128.32.84, type: ss,"name":"FR_57.128.32.84_1026202301d8-355ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 46.183.184.64, type: ss,"name":"HR_46.183.184.64_1026202301d8-363ss"}
  - {network: tcp, password: telegram-id-directvpn, port: 22222, server: 18.153.119.231, skip-cert-verify: true, sni: trj.rollingnext.co.uk, type: trojan,"name":"DE_18.153.119.231_1026202301d8-369trojan"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 198.244.231.27, type: ss,"name":"GB_198.244.231.27_1026202301d8-372ss"}
  - {alterId: 64, cipher: auto, network: ws, port: 30000, server: 45.199.138.186, skip-cert-verify: true, tls: true, type: vmess, uuid: 4ec0ae62-de09-4029-904a-0313d4628ecf, ws-opts: {path: /path/1696682720138, headers: {host: www.19229362.xyz}},"name":"NL_45.199.138.186_1026202301d8-378vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 21106, server: cadld2.gophers.gay, skip-cert-verify: true, tls: false, type: vmess, uuid: 6713cd03-2cd4-49e9-9d8a-b768ee0a72fb, ws-opts: {path: /},"name":"US_40.233.66.40_1026202301d8-387vmess"}
  - {cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, port: 810, server: 51.178.87.37, type: ss,"name":"FR_51.178.87.37_1026202301d8-393ss"}
  - {cipher: chacha20-ietf-poly1305, password: NeVavl43FD6DgFoim7S6HGks, port: 51348, server: uk-c2261789.nip.io, type: ss,"name":"UA_194.38.23.137_1026202301d8-389ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 89.187.181.179, type: ss,"name":"US_89.187.181.179_1026202301d8-408ss"}
  - {password: telegram-id-directvpn, port: 22222, server: 13.43.69.5, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"GB_13.43.69.5_1026202301d8-410trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 45.155.249.151, servername: tms.dingtalk.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 9d5e69d2-46cf-4865-95fe-a2ee8c52a013, ws-opts: {path: /},"name":"NL_45.155.249.151_1026202301d8-420vmess"}
  - {cipher: aes-256-cfb, password: 2170f8, port: 14293, server: 45.55.2.232, type: ss,"name":"US_45.55.2.232_1026202301d8-432ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 103.75.118.27, type: ss,"name":"JP_103.75.118.27_1026202301d8-439ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: cloudflare.binghe.design, skip-cert-verify: false, tls: true, type: vmess, uuid: 4548b8de-c6f5-41f2-8cb6-723c8db8ed03, ws-opts: {path: /, headers: {Host: us.binghe.design}},"name":"CLOUDFLARE_104.16.68.38_1026202301d8-428vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.202.175, type: ss,"name":"NL_51.158.202.175_1026202301d8-452ss"}
  - {cipher: chacha20-ietf-poly1305, password: g13S7doXar0A, port: 443, server: 205.134.180.137, type: ss,"name":"US_205.134.180.137_1026202386f4-463ss"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: odelia.autos, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {Host: odelia.autos}},"name":"CLOUDFLARE_104.21.21.88_1026202301d8-447vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 3306, server: 38.121.43.71, type: ss,"name":"US_38.121.43.71_1026202386f4-471ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 146.59.110.167, type: ss,"name":"FR_146.59.110.167_1026202386f4-474ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: 172.233.194.102, skip-cert-verify: false, tls: false, type: vmess, uuid: 29b88e63-9092-4375-a551-c4ee4702cfbe, ws-opts: {path: /, headers: {Host: tms.dingtalk.com}},"name":"US_172.233.194.102_1026202386f4-481vmess"}
  - {cipher: chacha20-ietf-poly1305, password: 5cp9Z3iWnJZ2, port: 443, server: 205.134.180.151, type: ss,"name":"US_205.134.180.151_1026202386f4-498ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 110, server: 143.244.43.216, type: ss,"name":"CA_143.244.43.216_1026202386f4-568ss"}
