# Fri Sep 29 16:15:22 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Fri Sep 29 16:15:22 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 18.183.208.50, type: ss,"name":"JP_18.183.208.50_09292023d4b4-271ss"}
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 13.250.108.170, type: ss,"name":"SG_13.250.108.170_09292023d4b4-276ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 92.38.163.53, type: ss,"name":"LU_92.38.163.53_09292023d4b4-285ss"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 3306, server: 142.202.48.7, type: ss,"name":"US_142.202.48.7_09292023d4b4-288ss"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 192.71.249.78, type: ss,"name":"BE_192.71.249.78_09292023d4b4-294ss"}
  - {alterId: 64, cipher: auto, network: tcp, port: 42952, server: 156.245.8.145, skip-cert-verify: true, tls: false, type: vmess, uuid: 63b4b829-7f01-4e26-b037-f04b1f098765,"name":"HK_156.245.8.145_09292023d4b4-297vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: 5000, server: 172.99.188.99, type: ss,"name":"NL_172.99.188.99_09292023d4b4-300ss"}
  - {cipher: aes-256-gcm, password: KixLvKzwjekG00rm, port: 8080, server: ak1661.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"GB_51.68.206.229_09292023d4b4-261ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 55455, server: hkt.123ddns.xyz, skip-cert-verify: true, tls: true, type: vmess, uuid: d2ce45e6-9f22-492d-d81d-d639067a7583, ws-opts: {path: /},"name":"HK_112.120.244.43_09292023d4b4-313vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: sg-v.sshmax.xyz, skip-cert-verify: false, tls: false, type: vmess, uuid: 0baaf014-af04-4028-be53-f5c75bb276ae, ws-opts: {path: /vmess, headers: {Host: sg-v.sshmax.xyz}},"name":"SG_194.233.81.125_09292023d4b4-274vmess"}
  - {alterId: 64, cipher: auto, network: tcp, port: 52792, server: 156.225.67.102, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"US_156.225.67.102_09292023d4b4-316vmess"}
  - {cipher: aes-256-cfb, password: 2170f8, port: 14293, server: 45.55.2.232, type: ss,"name":"US_45.55.2.232_09292023d4b4-324ss"}
  - {alterId: 64, cipher: auto, network: tcp, port: 39661, server: 45.199.138.229, skip-cert-verify: true, tls: false, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24,"name":"MU_45.199.138.229_09292023d4b4-331vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 192.74.228.187, skip-cert-verify: false, tls: true, type: vmess, uuid: 051b844f-efe3-4847-92aa-66b5de0b6d4e, ws-opts: {path: /path/1695466421619, headers: {Host: www.59274706.xyz}},"name":"US_192.74.228.187_09292023d4b4-353vmess"}
  - {cipher: aes-256-cfb, password: f8f7aCzcPKbsF8p3, port: 989, server: 51.15.27.48, type: ss,"name":"FR_51.15.27.48_09292023d4b4-356ss"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 198.2.215.98, skip-cert-verify: false, tls: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /path/1694429908748, headers: {Host: www.59977650.xyz}},"name":"US_198.2.215.98_09292023d4b4-361vmess"}
  - {alterId: 1, cipher: auto, network: ws, port: 443, server: octavi.cfd, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: linkvws, headers: {host: octavi.cfd}},"name":"CLOUDFLARE_172.67.179.37_09292023d4b4-376vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.20.75.10, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_104.20.75.10_09292023d4b4-382vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: codepen.io, skip-cert-verify: false, tls: true, type: vmess, uuid: 03fcc618-b93d-6796-6aed-8a38c975d581, ws-opts: {path: '/octavi.cfd:443/linkvws', headers: {Host: sub.yifenjichang.top}},"name":"CLOUDFLARE_104.17.14.48_09292023d4b4-385vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 8880, server: ns1.v2-vip.fun, skip-cert-verify: true, tls: false, type: vmess, uuid: 617c9bc4-4116-41c6-99e0-ace49a38fcdb, ws-opts: {path: /Jnv8ViZOUVgijjOh0p5uGjHnXIiY, headers: {host: fr7.tehme100.fun}},"name":"CLOUDFLARE_172.67.229.32_09292023d4b4-390vmess"}
  - {cipher: aes-256-cfb, obfs: tls1.2_ticket_auth, obfs-param: "", password: eAokbaDN6, port: 8081, protocol: origin, protocol-param: "", server: jp-am48-6.eqnode.net, type: ssr,"name":"JP_52.195.170.64_09292023d4b4-363ssr"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.17.88.212, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_104.17.88.212_09292023d4b4-395vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.27.1.133, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_104.27.1.133_09292023d4b4-399vmess"}
  - {cipher: chacha20-ietf-poly1305, password: ezesBXesf3RKBCp1vqKuIx, port: 8080, server: beeconf.xyz, type: ss,"name":"DE_139.162.133.59_09292023d4b4-371ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 172.64.150.2, tls: true, type: vmess, uuid: 172dc69f-3b43-4457-8ef8-d555b2d37f4a, ws-opts: {path: /MScKp0V1fOrj1KT78dJc2lG, headers: {host: service3.karop.homes}},"name":"CLOUDFLARE_172.64.150.2_09292023d4b4-414vmess"}
  - {alterId: 64, cipher: auto, network: ws, port: 443, server: 198.2.207.100, skip-cert-verify: false, tls: true, type: vmess, uuid: 418048af-a293-4b99-9b0c-98ca3580dd24, ws-opts: {path: /path/1695177062956, headers: {Host: www.27790575.xyz}},"name":"US_198.2.207.100_09292023d4b4-420vmess"}
  - {cipher: aes-256-cfb, password: amazonskr05, port: 443, server: 13.114.44.98, type: ss,"name":"JP_13.114.44.98_09292023d4b4-430ss"}
