# Thu Oct 19 16:16:08 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Thu Oct 19 16:16:08 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.200.145, type: ss,"name":"FR_51.158.200.145_10192023432d-315ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.202.195, type: ss,"name":"NL_51.158.202.195_10192023432d-325ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.84.198, type: ss,"name":"FR_162.19.84.198_10192023432d-337ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.83.12, type: ss,"name":"FR_162.19.83.12_10192023432d-346ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: wnd3.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 10ea3b2a-b615-45f1-b1b7-c62bafe8c80c, ws-opts: {path: /, headers: {Host: wnd3.shabijichang.com}},"name":"CLOUDFLARE_172.64.80.1_10192023432d-347vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.37.72, type: ss,"name":"FR_51.158.37.72_10192023432d-349ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 51.158.200.138, type: ss,"name":"FR_51.158.200.138_10192023432d-357ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 2053, server: 45.76.85.74, skip-cert-verify: false, tls: false, type: vmess, uuid: 4134efe7-d935-416c-c2cc-24943e4a80ca, ws-opts: {path: /},"name":"DE_45.76.85.74_10192023432d-371vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: fhc2.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: c458695d-6908-45c3-9512-e0c46418454c, ws-opts: {path: /, headers: {Host: fhc2.shabijichang.com}},"name":"CLOUDFLARE_104.21.75.246_10192023432d-377vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: hdlb3.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 10ea3b2a-b615-45f1-b1b7-c62bafe8c80c, ws-opts: {path: /, headers: {Host: hdlb3.shabijichang.com}},"name":"CLOUDFLARE_172.67.184.13_10192023432d-383vmess"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 146.59.55.84, type: ss,"name":"FR_146.59.55.84_10192023432d-406ss"}
