# Sat Oct 21 08:14:30 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Sat Oct 21 08:14:30 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-gcm, password: faBAoD54k87UJG7, port: 2376, server: ak1820.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"DE_217.182.198.219_102120233b07-231ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: hdlb3.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 10ea3b2a-b615-45f1-b1b7-c62bafe8c80c, ws-opts: {path: /, headers: {Host: hdlb3.shabijichang.com}},"name":"CLOUDFLARE_172.67.184.13_102120233b07-245vmess"}
  - {password: telegram-id-directvpn, port: 22222, server: 52.18.70.87, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"IE_52.18.70.87_102120233b07-247trojan"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: 443, server: 162.19.18.107, type: ss,"name":"FR_162.19.18.107_102120233b07-267ss"}
  - {password: telegram-id-privatevpns, port: 22222, server: 34.242.251.75, skip-cert-verify: false, sni: trj.rollingnext.co.uk, type: trojan,"name":"IE_34.242.251.75_102120233b07-270trojan"}
  - {alterId: 0, cipher: auto, network: ws, port: 80, server: jd2.shabijichang.com, skip-cert-verify: false, tls: false, type: vmess, uuid: 56278a1a-c7cc-459f-b00c-3037e4f99590, ws-opts: {path: /, headers: {Host: jd2.shabijichang.com}},"name":"CLOUDFLARE_172.64.80.1_102120233b07-274vmess"}
