# Wed Sep 13 10:09:56 UTC 2023
ipv6: true
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
#external-ui: clash_webs
external-controller: 127.0.0.1:9090
tunnels: ["tcp/udp,0.0.0.0:7891,[::1]:7890,DIRECT"]
rules:  
  - GEOIP,CN,DIRECT
  - SRC-IP-CIDR,0.0.0.0/0,A0 
  - MATCH,B0
proxy-providers:
  pr:
    type: http
    interval: 9600
    url: "https://cdn.jsdelivr.net/gh/c83a/clash233/config.yml"
    path: r.yml
    # filter: '^[^C]|^C[^N]'
    health-check:
      enable: true
      lazy: true
      interval: &seconds 3600
      url: &baidu https://www.baidu.com/
proxy-groups:
  - {name: "@ Wed Sep 13 10:09:56 UTC 2023", type: select, proxies: [REJECT]}
  - {name: A0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: B0, type: select, proxies: [A1,E0,DIRECT]}
  - {name: E0, type: select, use: [pr], proxies: [REJECT]}
  - {name: A1, type: load-balance, use: [pr], url: *baidu, interval: *seconds, strategy: round-robin}
proxies:
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: "5001", server: ak1767.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"PL_51.77.53.200_091320235ce1-1547ss"}
  - {cipher: chacha20-ietf-poly1305, password: c3ebc942-7f99-4d7c-9626-98a143b3832c, port: "20112", server: tr-02.feitudy.xyz, type: ss,"name":"HK_212.192.15.145_091320235ce1-1560ss"}
  - {cipher: chacha20-ietf-poly1305, password: c3ebc942-7f99-4d7c-9626-98a143b3832c, port: "20111", server: tr-01.feitudy.xyz, type: ss,"name":"HK_212.192.12.191_091320235ce1-1563ss"}
  - {cipher: chacha20-ietf-poly1305, password: c3ebc942-7f99-4d7c-9626-98a143b3832c, port: "20202", server: jp-02.feitudy.xyz, type: ss,"name":"JP_103.230.15.132_091320235ce1-1565ss"}
  - {cipher: aes-256-cfb, password: asdKkaskJKfnsa, port: "443", server: 162.19.59.164, type: ss,"name":"FR_162.19.59.164_091320235ce1-1628ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: dongtaiwang2.com, skip-cert-verify: false, tls: true, type: vmess, uuid: 87a95522-985c-4a17-afea-9b7d7208bce5, ws-opts: {path: /dongtaiwang.com, headers: {Host: 3.freek1.xyz}},"name":"CLOUDFLARE_23.227.38.113_091320235ce1-1645vmess"}
  - {cipher: aes-256-gcm, password: Y6R9pAtvxxzmGC, port: "5600", server: ak1599.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"FR_149.202.82.172_091320235ce1-1833ss"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 104.21.209.83, tls: true, type: vmess, uuid: 5bba02dd-96c1-4a3d-ac1c-ac162025be9a, ws-opts: {path: /aHFYCl4zLtepo0YwKHeQ, headers: {host: service4.karop.homes}},"name":"CLOUDFLARE_104.21.209.83_091320235ce1-2859vmess"}
  - {alterId: 0, cipher: auto, network: ws, port: 443, server: 172.64.150.2, tls: true, type: vmess, uuid: 5bba02dd-96c1-4a3d-ac1c-ac162025be9a, ws-opts: {path: /aHFYCl4zLtepo0YwKHeQ, headers: {host: service4.karop.homes}},"name":"CLOUDFLARE_172.64.150.2_091320235ce1-3265vmess"}
  - {cipher: chacha20-ietf-poly1305, password: G!yBwPWH3Vao, port: 810, server: ak1774.www.outline.network.fr8678825324247b8176d59f83c30bd94d23d2e3ac5cd4a743bkwqeikvdyufr.cyou, type: ss,"name":"JP_185.172.113.182_091320235ce1-4115ss"}
